$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: flask-demo-app-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: flask-demo-app
  ports:
    - protocol: TCP
      port: 8883
      targetPort: 8080